// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFG01u-x9dK23O2j1DQVYI_in3boVvfZA',
    appId: '1:158875253048:web:39abcc98b6d8c885d229cd',
    messagingSenderId: '158875253048',
    projectId: 'mynotes-585b6',
    authDomain: 'mynotes-585b6.firebaseapp.com',
    storageBucket: 'mynotes-585b6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBjDl73UucisLx-WWWbVmUe2PSLz6KQQo',
    appId: '1:158875253048:android:a0afbbec827ce22fd229cd',
    messagingSenderId: '158875253048',
    projectId: 'mynotes-585b6',
    storageBucket: 'mynotes-585b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsHrW5SI13ajzJRo38E6XKbq05WzY3ku8',
    appId: '1:158875253048:ios:7e1b5f4877af63cbd229cd',
    messagingSenderId: '158875253048',
    projectId: 'mynotes-585b6',
    storageBucket: 'mynotes-585b6.appspot.com',
    iosClientId: '158875253048-3pf6n6jb2jlp8luvosu4h0qcge5ah5bh.apps.googleusercontent.com',
    iosBundleId: 'com.fernandogarciag.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsHrW5SI13ajzJRo38E6XKbq05WzY3ku8',
    appId: '1:158875253048:ios:7e1b5f4877af63cbd229cd',
    messagingSenderId: '158875253048',
    projectId: 'mynotes-585b6',
    storageBucket: 'mynotes-585b6.appspot.com',
    iosClientId: '158875253048-3pf6n6jb2jlp8luvosu4h0qcge5ah5bh.apps.googleusercontent.com',
    iosBundleId: 'com.fernandogarciag.mynotes',
  );
}
